package scaffold

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Generate", func() {
	It("creates the function source files for a Go function", func() {
		files, err := Generate(Config{
			Name:      "my-func",
			Runtime:   "go",
			Registry:  "image-registry.openshift-image-registry.svc:5000/default",
			Namespace: "default",
		})

		Expect(err).NotTo(HaveOccurred())
		Expect(files).NotTo(BeEmpty())

		fileMap := map[string]string{}
		for _, f := range files {
			fileMap[f.Path] = f.Content
			Expect(f.Mode).NotTo(BeEmpty())
			Expect(f.Type).To(Equal("blob"))
		}

		Expect(fileMap).To(HaveKey("func.yaml"))
		funcYAML := fileMap["func.yaml"]
		Expect(funcYAML).To(ContainSubstring("my-func"))
		Expect(funcYAML).To(ContainSubstring("go"))
		Expect(funcYAML).To(ContainSubstring("image-registry.openshift-image-registry.svc:5000/default"))

		Expect(fileMap).NotTo(HaveKey(".github/workflows/func-deploy.yaml"),
			"CI workflow is SCM-specific and should not be generated by scaffold")
	})

	DescribeTable("produces files for all supported runtimes",
		func(runtime string) {
			files, err := Generate(Config{
				Name:      "test-fn",
				Runtime:   runtime,
				Registry:  "quay.io/myuser",
				Namespace: "default",
			})
			Expect(err).NotTo(HaveOccurred())
			Expect(files).NotTo(BeEmpty())
		},
		Entry("node", "node"),
		Entry("python", "python"),
		Entry("go", "go"),
		Entry("quarkus", "quarkus"),
	)
})
